export const ERROR = "ERROR";
export const MOVIES_UPDATE = "MOVIES_UPDATE";
export const SELECTED_MOVIE_UPDATE = "SELECTED_MOVIE_UPDATE";
export const SEARCHED_MOVIES_UPDATE = "SEARCHED_MOVIES_UPDATE";